import type {
	PortfolioCommandCenterSnapshot,
	PortfolioPaymentDetail,
	PortfolioPositionDetail,
} from "./portfolio-types";

export const portfolioCommandCenterFixture: PortfolioCommandCenterSnapshot = {
	actionsRequired: {
		allClear: false,
		items: [
			{
				dueDate: "2026-04-28",
				id: "action_renewal_king",
				kind: "renewal_prompt",
				mortgageId: "mortgage_king",
				prefillContext: {
					contextType: "mortgage",
					mortgageId: "mortgage_king",
					propertyLabel: "123 King St W, Toronto",
					subjectId: "mortgage_king",
					summary:
						"Renewal intent is awaiting lender decision with status pending_signal",
					title: "Review King Street renewal",
				},
				priority: "high",
				status: "pending_signal",
				summary:
					"Renewal intent is awaiting lender decision with status pending_signal",
				title: "Review renewal decision",
			},
			{
				dueDate: "2026-04-01",
				id: "action_payment_overdue",
				kind: "payment_exception",
				mortgageId: "mortgage_king",
				obligationId: "obligation_overdue",
				prefillContext: {
					contextType: "payment",
					mortgageId: "mortgage_king",
					obligationId: "obligation_overdue",
					propertyLabel: "123 King St W, Toronto",
					subjectId: "obligation_overdue",
					summary: "Collection follow-up required for overdue lender payment.",
					title: "Investigate overdue payment",
				},
				priority: "high",
				status: "overdue",
				summary: "Collection follow-up required for overdue lender payment.",
				title: "Investigate overdue payment",
			},
		],
	},
	brokerCoordination: {
		assignedBroker: {
			brokerId: "broker_meridian",
			brokerageName: "Meridian Brokerage",
			email: "broker@fairlend.ca",
			name: "Morgan Broker",
			phoneNumber: "416-555-0100",
		},
		availabilityState: "fallback_contact_only",
		fallbackContactCta: {
			label: "Email Morgan Broker",
			mode: "email",
			value: "broker@fairlend.ca",
		},
		prefillContextPayloads: {
			dealFollowUps: [],
			mortgageFollowUps: [
				{
					contextType: "mortgage",
					mortgageId: "mortgage_king",
					propertyLabel: "123 King St W, Toronto",
					subjectId: "mortgage_king",
					summary: "Discuss the renewal decision for the King Street mortgage.",
					title: "Discuss renewal timing",
				},
			],
			paymentFollowUps: [
				{
					contextType: "payment",
					mortgageId: "mortgage_king",
					obligationId: "obligation_overdue",
					propertyLabel: "123 King St W, Toronto",
					subjectId: "obligation_overdue",
					summary: "Coordinate next steps for the overdue payment.",
					title: "Escalate overdue payment",
				},
			],
		},
		threadId: null,
	},
	cockpit: {
		breakdowns: {
			byMortgageStatus: [
				{ count: 1, key: "active", positionUnits: 6000 },
				{ count: 1, key: "delinquent", positionUnits: 4000 },
			],
			byPropertyType: [
				{ count: 2, key: "Detached Home", positionUnits: 10_000 },
			],
		},
		metrics: {
			activeDealCount: 1,
			activePositionCount: 2,
			availableCashBalance: 5000,
			estimatedPortfolioValue: 360_000,
			lifetimeAccruedInterest: 24_000,
			monthlyAccruedInterest: 2200,
			paymentExceptionCount: 1,
			renewalsDueSoonCount: 1,
			totalFractions: 10,
			totalPositionUnits: 10_000,
			undisbursedBalance: 1200,
			weightedAverageInterestRate: 8.2,
			ytdAccruedInterest: 9000,
		},
	},
	emptyStates: {
		hasActions: true,
		hasPayments: true,
		hasPositions: true,
		hasSuggestions: true,
	},
	generatedAt: 1_710_000_500_000,
	limitsStrip: {
		constraints: {
			allowedMortgageTypes: ["First"],
			allowedPropertyTypes: ["Detached Home"],
			interestRateRange: { max: 10, min: 6.5 },
			loanAmountRange: { max: 450_000, min: 200_000 },
			ltvRange: { max: 0.75, min: 0.55 },
			maturityDateMax: "2027-12-31",
			updatedAt: 1_710_000_500_000,
		},
		effectiveFilters: {
			interestRate: { max: 10, min: 6.5 },
			ltv: { max: 0.75, min: 0.55 },
			maturityDate: { end: "2027-12-31" },
			mortgageTypes: ["First"],
			principalAmount: { max: 450_000, min: 200_000 },
			propertyTypes: ["Detached Home"],
			searchQuery: undefined,
		},
		hasConstraints: true,
		suggestionSeedCount: 2,
	},
	paymentActivity: {
		rows: [
			{
				dueDate: "2026-04-01",
				grossAmount: 1250,
				latestCollectionStatus: "failed",
				latestTransferStatus: "pending",
				lenderShareAmount: 750,
				mortgageId: "mortgage_king",
				obligationId: "obligation_overdue",
				obligationStatus: "overdue",
				paymentNumber: 4,
				propertyLabel: "123 King St W, Toronto",
				rowStatus: "overdue",
				type: "scheduled",
			},
			{
				dueDate: "2026-06-01",
				grossAmount: 980,
				latestCollectionStatus: "scheduled",
				latestTransferStatus: "queued",
				lenderShareAmount: 620,
				mortgageId: "mortgage_queen",
				obligationId: "obligation_upcoming",
				obligationStatus: "scheduled",
				paymentNumber: 5,
				propertyLabel: "88 Queen St W, Toronto",
				rowStatus: "upcoming",
				type: "scheduled",
			},
		],
	},
	positions: {
		rows: [
			{
				estimatedPositionValue: 220_000,
				fractionCount: 6,
				lenderSharePaymentAmount: 750,
				mortgageId: "mortgage_king",
				mortgageStatus: "active",
				nextPaymentDate: "2026-05-01",
				paymentAmount: 1250,
				positionPercent: 60,
				positionUnits: 6000,
				propertyLabel: "123 King St W, Toronto",
				renewalIntentStatus: "pending_signal",
				renewalTimingLabel: "Review due in 45 days",
				thumbnailUrl: "https://images.example.com/king-street.jpg",
			},
			{
				estimatedPositionValue: 140_000,
				fractionCount: 4,
				lenderSharePaymentAmount: 620,
				mortgageId: "mortgage_queen",
				mortgageStatus: "delinquent",
				nextPaymentDate: "2026-04-15",
				paymentAmount: 980,
				positionPercent: 40,
				positionUnits: 4000,
				propertyLabel: "88 Queen St W, Toronto",
				renewalIntentStatus: null,
				renewalTimingLabel: "Servicing follow-up active",
				thumbnailUrl: null,
			},
		],
	},
	sourceOfTruth: {
		cockpitMetrics: "ledger + accrual contract",
		csvTaxExportInputs: "portfolio export contract",
		historicalChartInputs: "snapshot pipeline",
		paymentActivityRows: "obligations + collection attempts",
	},
	suggestedOpportunities: {
		excludedOwnedMortgageCount: 1,
		rows: [
			{
				explanationTags: [
					{
						label: "Matches detached allocation",
						reason: "The listing fits the current detached-home concentration.",
					},
				],
				heroImageUrl: null,
				interestRate: 8.4,
				listingId: "listing_fresh",
				locationLabel: "Toronto, ON",
				ltvRatio: 0.64,
				marketplaceCopy: "Fresh lender opportunity",
				maturityDate: "2027-08-01",
				mortgageId: null,
				mortgageTypeLabel: "First",
				principal: 250_000,
				propertyTypeLabel: "Detached Home",
				title: "Fresh Opportunity",
			},
		],
	},
};

export const emptyPortfolioCommandCenterFixture: PortfolioCommandCenterSnapshot =
	{
		...portfolioCommandCenterFixture,
		actionsRequired: { allClear: true, items: [] },
		cockpit: {
			...portfolioCommandCenterFixture.cockpit,
			metrics: {
				...portfolioCommandCenterFixture.cockpit.metrics,
				activeDealCount: 0,
				activePositionCount: 0,
				availableCashBalance: 0,
				estimatedPortfolioValue: 0,
				lifetimeAccruedInterest: 0,
				monthlyAccruedInterest: 0,
				paymentExceptionCount: 0,
				renewalsDueSoonCount: 0,
				totalFractions: 0,
				totalPositionUnits: 0,
				undisbursedBalance: 0,
				weightedAverageInterestRate: 0,
				ytdAccruedInterest: 0,
			},
		},
		emptyStates: {
			hasActions: false,
			hasPayments: false,
			hasPositions: false,
			hasSuggestions: false,
		},
		limitsStrip: {
			...portfolioCommandCenterFixture.limitsStrip,
			hasConstraints: false,
		},
		paymentActivity: { rows: [] },
		positions: { rows: [] },
		suggestedOpportunities: {
			excludedOwnedMortgageCount: 0,
			rows: [],
		},
	};

export const portfolioPositionDetailFixture: PortfolioPositionDetail = {
	generatedAt: 1_710_000_500_000,
	mortgage: {
		amortizationMonths: 240,
		firstPaymentDate: "2026-02-01",
		interestRate: 8.5,
		lienPosition: 1,
		maturityDate: "2027-01-01",
		mortgageId: "mortgage_king",
		paymentAmount: 1250,
		paymentFrequency: "monthly",
		principal: 250_000,
		rateType: "fixed",
		status: "active",
		termMonths: 12,
	},
	paymentOverview: {
		lenderSharePaymentAmount: 750,
		nextPaymentDate: "2026-05-01",
	},
	position: portfolioCommandCenterFixture.positions.rows[0],
	property: {
		city: "Toronto",
		heroImageUrl: "https://images.example.com/king-street-hero.jpg",
		postalCode: "M5V1E3",
		propertyType: "Detached Home",
		province: "ON",
		streetAddress: "123 King St W",
		unit: null,
	},
	quickActions: [
		portfolioCommandCenterFixture.actionsRequired.items[0],
		{
			dealId: "deal_king",
			dueDate: null,
			id: "action_open_deal",
			kind: "deal_action",
			mortgageId: "mortgage_king",
			prefillContext: {
				contextType: "deal",
				dealId: "deal_king",
				propertyLabel: "123 King St W, Toronto",
				subjectId: "deal_king",
				summary: "Open the linked deal package for the King Street mortgage.",
				title: "Open linked deal",
			},
			priority: "medium",
			status: "ready",
			summary: "Open the linked deal package for the King Street mortgage.",
			title: "Open linked deal",
		},
	],
	renewal: {
		brokerAcknowledgedAt: null,
		intent: "renew",
		partialExitFractions: null,
		signalDeadline: "2026-05-15",
		status: "pending_signal",
	},
};

export const portfolioPaymentDetailFixture: PortfolioPaymentDetail = {
	collectionTimeline: [
		{
			label: "Payment scheduled",
			status: "scheduled",
			timestampLabel: "Apr 1, 2026",
		},
		{
			label: "Collection attempt created",
			status: "failed",
			timestampLabel: "Apr 2, 2026",
		},
	],
	generatedAt: 1_710_000_500_000,
	mortgage: {
		interestRate: 8.5,
		maturityDate: "2027-01-01",
		mortgageId: "mortgage_king",
		paymentAmount: 1250,
		paymentFrequency: "monthly",
		principal: 250_000,
		status: "active",
	},
	payment: portfolioCommandCenterFixture.paymentActivity.rows[0],
	positionSummary: {
		estimatedPositionValue: 220_000,
		lenderSharePercent: 60,
		positionUnits: 6000,
	},
	property: {
		city: "Toronto",
		propertyType: "Detached Home",
		province: "ON",
		streetAddress: "123 King St W",
		unit: null,
	},
	relatedActions: portfolioCommandCenterFixture.actionsRequired.items,
};
